DELETE FROM tm_afmeisyo_main WHERE 1=1;
DELETE FROM tm_afhanyo_main WHERE 1=1;
DELETE FROM tm_afctrl_main WHERE 1=1;
--tm_afmeisyo_main(一覧)
INSERT INTO tm_afmeisyo_main VALUES('1000', 1, 'メニュー', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 2, '名称マスタメインコード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 3, '汎用マスタメインコード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 4, 'コントロールマスタメインコード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 6, 'データ型', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 7, '連携処理区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 8, 'DB変更区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 9, 'メッセージ切替区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 10, 'ファイルタイプ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 11, '性別_システム', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 12, '処理結果コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 13, '表示色コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 14, 'フリー項目データタイプ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 15, '独自施策項目パターン', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 16, 'ファイルマスタ使用区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 17, '事業集約コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 18, '文字コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 19, '引用符_CSV出力用', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 20, '共通バー番号_共通機能', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 21, '共通バー表示', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 22, '処理一覧_ログ画面用', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 24, '指定コード長さ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 26, '詳細条件コントローラー', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 27, '一覧テーブル区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 28, '画面項目入力コントローラー', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 29, '住登区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 30, '連携方式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 31, '連絡先タブ区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 32, '年号情報', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 38, 'ログ区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 39, '連携方向区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 40, '操作処理区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 41, '住民区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 42, '住民区分設定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 44, '停止フラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 45, '最新フラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 46, '拡事業業務', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 47, '拡事業種類', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 48, '事業区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 49, '項目区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 50, '項目配置区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 51, '各種事業コード設定対象', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 52, '前回処理結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 53, 'モジュール', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 54, '月', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 55, '日', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 56, '週目', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 57, '曜日', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 58, '繰り返し間隔', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 59, '継続時間', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 61, '頻度区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 62, '状態_バッチ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 63, '使用停止フラグ_バッチ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 64, '連携区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 65, 'システム区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 66, '入出力区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 67, '連携先', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 68, 'チェック区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 69, '変換区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 70, 'エラーレベル_連携', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 71, 'ジョブステータス', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 72, '性別_システム共有', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 73, 'フリー項目特定区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 74, '年度範囲区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 75, '計算区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 76, '計算関数_内部', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1000', 77, 'グループ_基本データリスト', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 1, '保険区分_共通管理', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 5, '申込結果区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 6, '指導区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 7, 'フリー項目用途区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 12, 'コース区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 14, '取込区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 15, '登録区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 16, 'ファイル形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 17, 'エンコード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 18, 'データ形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 19, 'コード管理テーブル', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 20, '区切り記号', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 21, 'フォーマット_日付', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 22, '項目特定区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 23, 'マッピング区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 24, 'マッピング方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 25, '入力区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 26, '入力方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 27, 'フォーマット_画面定義', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 28, 'エラーレベル', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 29, '表示入力設定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 30, '演算子', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 31, '処理区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 32, '処理種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 33, '削除条件指定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 34, '地域保健集計区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 35, 'フォーマットチェック関数', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 36, 'フォーマット変換関数', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 37, '地区区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 38, '引数区分_マッピング', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 39, '全体個別区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 40, '項目管理区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 41, '抽出条件区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 42, '通知サイクル', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 43, '引数区分_項目定義', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 100, '医療機関_事業従事者業務区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 101, '拡_予約_保健指導業務区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 102, '基準値業務区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 103, 'EUC業務区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 104, '取込業務区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 105, 'システム業務区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 106, '_バッファ_画面業務区分106', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 107, '基本データリストデータ型', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1001', 199, '_バッファ_画面業務区分199', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 1, '成人保健フリー項目グループ１', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 3, '計算関数_内部_成人', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 4, '計算関数_DB_成人', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 7, '対象サイン', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 8, '精密検査実施区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 9, 'クーポン券表示区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 10, '減免区分種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 11, '年齢基準日区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 12, '対象サイン引継ぎフラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 13, '健_検_診対象者特殊条件', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 14, '計算区分_成人', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1002', 15, '生涯一回フラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 1, '出力形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 2, '帳票状態区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 3, '帳票分類', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 4, '様式種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 5, '集計種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 6, '専用様式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 10, '文字形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 11, '数値形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 12, '年形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 13, '日付形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 14, '日時形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 15, '時間形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 16, '論理形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 17, 'バーコード形式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 18, '出力方式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 19, '除票者除外区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('1006', 20, '検索区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 1, '性別_住民基本台帳', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 4, '住民種別_住民基本台帳', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 5, '住民状態_住民基本台帳', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 8, '第30条45規定区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 10, '在留資格等', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 11, '在留期間等コード年', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 12, '在留期間等コード月', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 13, '在留期間等コード日', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 14, '氏名優先区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 18, '続柄', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 20, '記載の事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 21, '消除の事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 22, '修正の事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2001', 32, '支援措置区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2010', 2, '未申告区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2010', 5, '課税非課税区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2010', 28, '税額_税額控除', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2010', 900001, '他団体課税対象者区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 2, '職種', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 3, '活動区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 4, '登録事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 5, '金額区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 7, '発行区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 8, '重要度', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 9, '訪問種別_訪問結果情報', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 10, '訪問対象', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 12, '栄養_運動等指導内容', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 20, '実施区分_個別/集団', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 21, '出欠区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 22, '相談内容', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 25, '個別健康教育対象者区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 26, '個別健康教育内容', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 27, '個別健康教育状態区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 28, '個別健康教育実施形態', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 29, '集団健康教育内容', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 32, '把握経路_フォロー状況情報', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 33, 'フォロー方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 34, 'フォロー状況', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 35, '成人保健の受診希望', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 37, '過去の受診歴', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 38, '自治体検診の問診における有無の回答_三択', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 39, 'がん検診による偶発症の有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 40, 'がん検診の精密検査による偶発症の有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 41, '血液判断', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 45, '胃がん検診の精密検査の対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 46, '胃がん検診の検査方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 47, '所見有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 48, '胃がん検診の精密検査結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 49, '肺がん検診の精密検査対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 51, '肺がん検診の胸部エックス線検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 52, '肺がん検診の喀痰検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 53, '肺がん検診の精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 55, '子宮頸がん検診の精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 56, '子宮頸がん検診の頸部細胞診検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 57, '子宮頸がん検診の精密検査の対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 58, '初回検体の適否', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 59, '骨粗鬆症検診の精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 60, '過去の検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 61, '過去の精密検査の対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 62, '喫煙習慣', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 63, 'ステロイド内服', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 64, '活動量_運動頻度', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 65, '月経の有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 66, '閉経の理由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 67, '骨粗鬆症検診の検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 68, '歯周疾患検診の精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 69, '歯周疾患検診の精密検査の対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 70, '歯をみがく頻度', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 71, '歯間ブラシやフロスの使用頻度', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 72, '喫煙歴', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 73, '歯肉出血ＢＯＰ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 74, '歯周ポケットＰＤ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 75, '歯石の付着', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 76, '口腔清掃状態', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 77, '便潜血検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 78, '大腸がん検診の精密検査の対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 79, '大腸がん検診の精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 80, '乳がん検診のマンモグラフィー検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 81, '乳がん検診の精密検査対象有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 82, '乳がん検診_マンモグラフィー検査一次読影', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 83, '乳がん検診_マンモグラフィー検査二次読影', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 84, '乳がん検診の精密検査結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 85, '肝炎ウイルス検診のB 型肝炎ウイルス検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 86, '肝炎ウイルス検診のC 型肝炎ウイルス検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 87, '肝炎ウイルス検診の精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 88, 'C型判定理由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 89, '届出事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 90, '届出時期_不詳含む', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 91, '交付事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 92, '受診区分_妊婦健診結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 93, '境界区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 94, 'ABO型', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 95, 'RH型', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 96, '境界区分４', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 97, '境界区分２', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 98, '風疹抗体', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 99, '子宮頸がん検診', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 100, '承認区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 101, '訪問理由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 102, '妊産婦区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 103, '歯科判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 104, '妊婦歯科歯肉の炎症', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 105, '精密検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 106, '精密検査結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 107, '産婦健診判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 108, '利用サービス', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 109, '栄養方法_新生児期', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 110, '先天性代謝異常等検査', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 111, '聴覚検査方式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 112, '聴覚検査結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 113, '聴覚検査判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 114, '助成券種類', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 115, '実施区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 116, '歳児別健診判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 117, '眼科の判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 118, '耳鼻科の判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 119, '栄養', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 120, '母乳', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 121, '離乳', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 122, '乳幼児健診アンケート回答_仕上げ磨き', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 123, '乳幼児健診アンケート回答_はい_いいえ_無回答', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 124, '乳幼児健診アンケート回答_子育て', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 125, '乳幼児健診アンケート回答_父親育児', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 126, '乳幼児健診アンケート回答_浴室ドア', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 127, '乳幼児健診アンケート回答_はい_いいえ_何ともいえない_無回答', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 128, '乳幼児健診アンケート回答_育てにくさ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 129, '罹患型１', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 130, 'むし歯の状態_3歳児健診結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 134, '不正咬合', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 136, '産後ケア', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 137, '栄養法_3～4か月児健診結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 139, '罹患型２', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 141, '所見または今後の処置', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 142, '勧奨方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 143, '訪問種別_訪問情報', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 144, '笑うことができたし、物事の面白い面もわかった', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 145, '物事を楽しみにして待った', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 146, '物事がうまくいかない時、自分を不必要に責めた', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 147, 'はっきりとした理由もないのに不安になったり、心配したりした', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 148, 'はっきりとした理由もないのに恐怖に襲われた', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 149, 'することがたくさんあって大変だった', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 150, '不幸せな気分なので、眠りにくかった', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 151, '悲しくなったり、惨めになったりした', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 152, '不幸せな気分だったので、泣いていた', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 153, '自分自身を傷つけるという考えが浮かんできた', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 154, '保健指導_対象者区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 155, '健康増進_実施対象者', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 156, '同伴者', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 157, '階層区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 158, '加算対象', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 159, '申請区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 160, '申請変更理由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 161, '保険区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 162, '課税区分_養育医療申請情報', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 163, '申請者_扶養義務者_続柄', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 164, '判定結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 167, 'レセプト区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 170, '予防接種の実施方式', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 171, '接種区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 172, '特別の事情', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 173, '単位', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 174, '接種判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 175, '抗体検査方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 176, '抗体検査番号', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 177, '認定区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 179, '給付の種類', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 180, '住民種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 181, '住民状態', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 187, '骨粗鬆症検診の一次検診判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 188, '大腿骨近位部骨折の家族歴', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 189, '予防接種区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 190, '健やか親子21アンケート回答_心身の調子', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 191, '健やか親子21アンケート回答_経済的状況', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 192, '健やか親子21アンケート回答_朝起きる時間', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 193, '健やか親子21アンケート回答_夜寝る時間', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 194, '健やか親子21アンケート回答_なし_あり_無回答', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 195, '健やか親子21アンケート回答_あり_なし_無回答', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 196, '健やか親子21アンケート回答_働いていたことがある', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 197, '健やか親子21アンケート回答_利用したことがある', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 198, 'マタニティマークアンケート回答_知らなかった_知っていた', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 199, '乳幼児歯科健診判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 200, '育児支援チェックリスト回答1～3、4_3_また5～9', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 201, '育児支援チェックリスト回答4_1', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 202, '育児支援チェックリスト回答4_2', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 203, '赤ちゃんへの気持ち質問票回答１', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 204, '赤ちゃんへの気持ち質問票回答２', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 205, '点数表コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 206, '療養_食事コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 207, '歯式コード_妊産婦', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 208, '歯式コード_子供', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 209, '住登外者異動事由', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 210, '妊婦健診判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 211, 'パーセンタイル値の範囲', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 212, '屈折検査判定結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 213, '食事をかんで食べる時の状態', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 214, '冷たいものや熱いものが歯にしみますか', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 215, 'ゆっくりよくかんで食事をしますか', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 216, '歯科医院にいつ頃行きましたか', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 217, '歯は何本ありますか', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 218, '歯式コード_成人', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 219, '診察所見の判定', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 220, 'はい_いいえ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 221, '健診種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 222, '子宮復古状況', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 223, '悪露', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 224, '分娩経過', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 225, '分娩方法', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 226, '出血量_区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 227, '出産時の児の状態_性別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 228, '歯周病', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 229, '歯周病の治療の必要', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 230, '特別な所見_処置', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 231, '異常', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 232, '歯の汚れ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 233, '本人性別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 234, 'キャンセル待ち', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 235, '有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 236, '実施', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 237, '該当', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 238, '輸血の有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 239, '歯の形態_色調', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 240, 'いいえ_はい', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 241, '妊娠歴', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 242, '出産歴', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 243, 'むし歯の状態_1歳6か月児健診結果', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 244, '軟組織異常有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 245, '栄養法_3～4か月児健診アンケート', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 246, '要否', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 247, '可_否', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2019', 900001, '有無区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2021', 19, '単併給区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2021', 900001, '認定有無', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2022', 8, '資格状態', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2022', 15, '身体障害者手帳障害種別', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2022', 16, '身体障害者手帳総合等級', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2022', 17, '身体障害者手帳障害部位', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2023', 35, '要介護状態区分コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2023', 49, '被保険者区分コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2023', 63, '要介護認定状況コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2024', 1, '国保資格区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2024', 7, 'マル学マル遠区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2024', 131, '国保資格取得事由_集約システム', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2024', 132, '国保資格喪失事由_集約システム', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2024', 900001, '証区分', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2025', 1, '個人区分コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2025', 11, '資格取得事由コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2025', 12, '資格喪失事由コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2031', 2, '名寄せ元フラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2031', 3, '他業務参照不可フラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2032', 1, '性別_団体内統合宛名', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('2032', 3, '統合宛名フラグ', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('3019', 100002, '国名コード', NULL, NULL, NULL, NULL);
INSERT INTO tm_afmeisyo_main VALUES('3019', 100004, '指定都市_行政区等コード', NULL, NULL, NULL, NULL);
--tm_afhanyo_main(一覧)
INSERT INTO tm_afhanyo_main VALUES('1000', 1, 'メモ事業コード管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 2, '電子ファイル事業コード管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 3, '医療機関事業コード管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 4, '事業従事者事業コード管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 5, '連絡先事業コード管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 6, 'フォロー事業コード管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 8, '祝日管理', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1000', 9, '計算関数_DB', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1001', 1, '自治体情報', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1001', 2, '課', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1001', 3, '係', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1001', 4, '問い合わせ内容コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1001', 5, 'クーポン券発番順', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 1, '受診拒否理由', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 2, '成人健_検_診予約日程事業名', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 3, '料金パターン', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 4, '減免区分_がん検診', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 5, '減免区分_特定健診', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 101, '基本健診予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 102, '肝炎予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 103, '胃がん予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 104, '大腸がん予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 105, '肺がん予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 106, '子宮頸がん予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 107, '乳がん予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 108, '骨粗鬆症予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 109, '歯周疾患予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 110, '検診種別１０_予備_予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 151, '拡事業１予約分類', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 201, '基本検診フリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 202, '肝炎フリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 203, '胃がんフリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 204, '大腸がんフリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 205, '肺がんフリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 206, '子宮頸がんフリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 207, '乳がんフリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 208, '骨粗鬆症フリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 209, '歯周疾患フリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 210, '検診種別１０_予備_フリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1002', 251, '拡事業１_予備_フリー項目グループ2', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1006', 1, '業務区分_帳票', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1006', 2, '帳票グループ', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1006', 3, '帳票発行履歴区分', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1006', 100, '帳票出力区分紐づけ', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1006', 101, '帳票出力区分一覧', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('1006', 201, '出力区分管理様式一覧', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 1, '部署_支所', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 2, 'メモ事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 3, '電子ファイル事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 4, '連絡先用事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100001, '医師会', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100002, '保健指導_集団指導項目グループ', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100003, '医療機関_事業従事者_担当者_事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100004, '実施報告事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100005, '利用目的', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100006, 'フォロー把握事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100007, 'フォロー事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100008, '集団指導事業コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100009, '独自施策システム等ID', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100010, '業務ID', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 100011, '登録部署', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 200001, '検診種別', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210001, '基本健診一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210002, '基本健診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210201, '肝炎検診一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210202, '肝炎検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210401, '胃がん一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210402, '胃がん検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210601, '大腸がん一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210602, '大腸がん検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210801, '肺がん一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 210802, '肺がん検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211001, '子宮頸がん一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211002, '子宮頸がん検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211201, '乳がん一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211202, '乳がん検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211401, '骨粗鬆症一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211402, '骨粗鬆症検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211601, '歯周疾患一次検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211602, '歯周疾患検診用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 211801, '検診種別10_予備_用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 220001, 'PKG用精密検査コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 230001, '市区町村用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 240001, '市区町村用精密検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250001, '拡事業１検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250002, '拡事業１用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250201, '拡事業２検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250202, '拡事業２用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250401, '拡事業３検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250402, '拡事業３用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250601, '拡事業４検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250602, '拡事業４用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250801, '拡事業５検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 250802, '拡事業５用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251001, '拡事業６検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251002, '拡事業６用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251201, '拡事業７検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251202, '拡事業７用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251401, '拡事業８検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251402, '拡事業８用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251601, '拡事業９検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251602, '拡事業９用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251801, '拡事業１０検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 251802, '拡事業１０用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252001, '拡事業１１検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252002, '拡事業１１用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252201, '拡事業１２検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252202, '拡事業１２用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252401, '拡事業１３検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252402, '拡事業１３用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252601, '拡事業１４検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252602, '拡事業１４用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252801, '拡事業１５検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 252802, '拡事業１５用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253001, '拡事業１６検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253002, '拡事業１６用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253201, '拡事業１７検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253202, '拡事業１７用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253401, '拡事業１８検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253402, '拡事業１８用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253601, '拡事業１９検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253602, '拡事業１９用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253801, '拡事業２０検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 253802, '拡事業２０用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254001, '拡事業２１検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254002, '拡事業２１用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254201, '拡事業２２検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254202, '拡事業２２用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254401, '拡事業２３検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254402, '拡事業２３用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254601, '拡事業２４検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254602, '拡事業２４用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254801, '拡事業２５検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 254802, '拡事業２５用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255001, '拡事業２６検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255002, '拡事業２６用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255201, '拡事業２７検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255202, '拡事業２７用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255401, '拡事業２８検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255402, '拡事業２８用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255601, '拡事業２９検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255602, '拡事業２９用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255801, '拡事業３０検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 255802, '拡事業３０用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256001, '拡事業３１検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256002, '拡事業３１用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256201, '拡事業３２検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256202, '拡事業３２用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256401, '拡事業３３検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256402, '拡事業３３用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256601, '拡事業３４検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256602, '拡事業３４用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256801, '拡事業３５検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 256802, '拡事業３５用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257001, '拡事業３６検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257002, '拡事業３６用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257201, '拡事業３７検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257202, '拡事業３７用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257401, '拡事業３８検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257402, '拡事業３８用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257601, '拡事業３９検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257602, '拡事業３９用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257801, '拡事業４０検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 257802, '拡事業４０用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258001, '拡事業４１検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258002, '拡事業４１用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258201, '拡事業４２検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258202, '拡事業４２用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258401, '拡事業４３検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258402, '拡事業４３用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258601, '拡事業４４検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258602, '拡事業４４用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258801, '拡事業４５検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 258802, '拡事業４５用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259001, '拡事業４６検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259002, '拡事業４６用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259201, '拡事業４７検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259202, '拡事業４７用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259401, '拡事業４８検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259402, '拡事業４８用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259601, '拡事業４９検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259602, '拡事業４９用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259801, '拡事業５０検査方法', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 259802, '拡事業５０用一次検診コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 260001, '拡事業１用精密検査コード', NULL, NULL, NULL,false,false,false,NULL);
INSERT INTO tm_afhanyo_main VALUES('3019', 400001, '予防接種の帳票様式一覧', NULL, NULL, NULL,false,false,false,NULL);
--tm_afctrl_main(一覧)
INSERT INTO tm_afctrl_main VALUES('1000', 1, 'パスワード', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1000', 2, 'config情報', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1000', 3, '画面確認件数', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1000', 4, '画面上限件数', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1000', 5, '検診事業の年齢基準指定', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1000', 6, '検診事業の複数回数指定', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1000', 7, '拡事業関連上限件数', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1001', 2, '同一世帯員更新フラグ', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1001', 3, '付番開始番号', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1002', 2, '一次結果チェック区分', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1006', 1, 'テンプレート名', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1006', 2, 'アドレスシールの設定', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1006', 3, 'バーコードシールの設定', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1006', 4, 'はがきの設定', NULL, NULL, NULL);
INSERT INTO tm_afctrl_main VALUES('1006', 5, 'フォント表示の設定', NULL, NULL, NULL);