INSERT INTO tm_eutableitemname VALUES('111','名称マスタ ','tm_afmeisyo','nmcd','nm','nmmaincd','nmsubcd',False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('121','汎用マスタ','tm_afhanyo','hanyocd','nm','hanyomaincd','hanyosubcd',False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('122','汎用マスタ(カナ名称）','tm_afhanyo','hanyocd','nm','hanyomaincd','hanyosubcd',False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('123','汎用マスタ(略称）','tm_afhanyo','hanyocd','nm','hanyomaincd','hanyosubcd',False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('211','医療機関マスタ','tm_afkikan','hokenkikancd','kikannm',NULL,NULL,False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('221','ユーザーマスタ','tm_afuser','userid','usernm',NULL,NULL,False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('231','所属グループマスタ','tm_afsyozoku','syozokucd','syozokunm',NULL,NULL,False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('241','市区町村マスタ','tm_afsikutyoson','sikucd','sikunm',NULL,NULL,False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('251','地区情報マスタ','tm_aftiku','tikucd','tikunm','tikukbn',NULL,True) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('261','会場情報マスタ','tm_afkaijo','kaijocd','kaijonm',NULL,NULL,False) ON CONFLICT (mastercd) DO NOTHING;
INSERT INTO tm_eutableitemname VALUES('271','事業従事者担当者情報マスタ','tm_afstaff','staffid','staffsimei',NULL,NULL,False) ON CONFLICT (mastercd) DO NOTHING;