' ------------------------------------------------------------------------------
' <auto-generated>
' このコードはツールによって生成されました。
' ランタイム バージョン:4.0.30319.42000
' 
' このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
' コードが再生成されるときに損失したりします。
' </auto-generated>
' ------------------------------------------------------------------------------


Imports System.Diagnostics
Imports System.Globalization
Imports System.Runtime.CompilerServices
Imports Microsoft.VisualBasic

Namespace Jbd.Gjs.Service.My.Resources

    ' このクラスは StronglyTypedResourceBuilder クラスが ResGen
    ' または Visual Studio のようなツールを使用して自動生成されました。
    ' メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    ' ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    ''' <summary>
    ''' ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    ''' </summary>
    <CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
    <DebuggerNonUserCode()>
    <CompilerGenerated()>
    <HideModuleName()>
    Friend Module Resources

        Private resourceMan As System.Resources.ResourceManager

        Private resourceCulture As CultureInfo

        ''' <summary>
        ''' このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        ''' </summary>
        <ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)>
        Friend ReadOnly Property ResourceManager As System.Resources.ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp = New System.Resources.ResourceManager("MPS.Service.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        ''' すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ''' 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        ''' </summary>
        <ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As CultureInfo)
                resourceCulture = value
            End Set
        End Property
    End Module
End Namespace
