/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);
  
        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };
  
        return [singleLevelRoute];
      }
  
      if (isLayout(component)) {
        const layoutName = getLayoutName(component);
  
        vueRoute.component = layouts[layoutName];
      }
  
      if (isView(component)) {
        const viewName = getViewName(component);
  
        vueRoute.component = views[viewName];
      }
  
    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  
  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }
  
  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "gj10": "/gj10",
  "gj10_gj1010": "/gj10/gj1010",
  "gj10_gj1020": "/gj10/gj1020",
  "gj10_gj1030": "/gj10/gj1030",
  "gj10_gj1040": "/gj10/gj1040",
  "gj10_gj1050": "/gj10/gj1050",
  "gj10_gj1060": "/gj10/gj1060",
  "gj10_gj1070": "/gj10/gj1070",
  "gj20": "/gj20",
  "gj20_gj2010": "/gj20/gj2010",
  "gj20_gj2020": "/gj20/gj2020",
  "gj20_gj2030": "/gj20/gj2030",
  "gj20_gj2040": "/gj20/gj2040",
  "gj20_gj2050": "/gj20/gj2050",
  "gj20_gj2060": "/gj20/gj2060",
  "gj20_gj2070": "/gj20/gj2070",
  "gj20_gj2080": "/gj20/gj2080",
  "gj20_gj2090": "/gj20/gj2090",
  "gj20_gj2100": "/gj20/gj2100",
  "gj20_gj2110": "/gj20/gj2110",
  "gj20_gj2120": "/gj20/gj2120",
  "gj30": "/gj30",
  "gj30_gj3010": "/gj30/gj3010",
  "gj30_gj3020": "/gj30/gj3020",
  "gj30_gj3030": "/gj30/gj3030",
  "gj40": "/gj40",
  "gj40_gj4010": "/gj40/gj4010",
  "gj40_gj4020": "/gj40/gj4020",
  "gj40_gj4030": "/gj40/gj4030",
  "gj40_gj4040": "/gj40/gj4040",
  "gj40_gj4050": "/gj40/gj4050",
  "gj40_gj4060": "/gj40/gj4060",
  "gj40_gj4070": "/gj40/gj4070",
  "gj50": "/gj50",
  "gj50_gj5010": "/gj50/gj5010",
  "gj60": "/gj60",
  "gj60_gj6010": "/gj60/gj6010",
  "gj60_gj6020": "/gj60/gj6020",
  "gj60_gj6021": "/gj60/gj6021",
  "gj60_gj6030": "/gj60/gj6030",
  "gj60_gj6040": "/gj60/gj6040",
  "gj70": "/gj70",
  "gj70_gj7010": "/gj70/gj7010",
  "gj70_gj7020": "/gj70/gj7020",
  "gj70_gj7030": "/gj70/gj7030",
  "gj80": "/gj80",
  "gj80_gj8010": "/gj80/gj8010",
  "gj80_gj8020": "/gj80/gj8020",
  "gj80_gj8030": "/gj80/gj8030",
  "gj80_gj8040": "/gj80/gj8040",
  "gj80_gj8050": "/gj80/gj8050",
  "gj80_gj8060": "/gj80/gj8060",
  "gj80_gj8070": "/gj80/gj8070",
  "gj80_gj8080": "/gj80/gj8080",
  "gj80_gj8090": "/gj80/gj8090",
  "gj80_gj8100": "/gj80/gj8100",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "login": "/login/:module(pwd-login)?",
  "preview": "/preview",
  "todo": "/todo",
  "user-center": "/user-center"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
